### ISSUE TITLE
Discussion on formula (4), i.e. quantile quantization

### ISSUE THREAD

**Issue by zhu-yuefeng** [artidoro/qlora#94]
Glad to meet your marvelous QLoRA, especially with NF4. 
However, I fail to grasp the idea of formula 4 in the paper. You defiend $Q_x$ as the quantile function of standard normal distribution, which is often denoted as percent point function or `ppf` for short. It has been implemented, once as `scipy.stats.norm.ppf`. Both this  implementation and general definition shows that $Q_x(0)=-\infty$ which leads to $q_0=-\infty$. That NaN value cannot work well with the rest of deduction through out to the value table in Appendix E. 
Would you like to tell me either what goes wrong in my deduction, or where in code involves quantile quantization in practice? Thank you in advance!

**Comment by danitamayo** [comment]
I ran into the same doubt, and I found the implementation better explained in the paper "[NF4 Isn’t Information Theoretically Optimal](https://arxiv.org/pdf/2306.06965.pdf)." To explain it quickly, equation (4) is used for quantile quantization, but not for NormalFloat quantization because "[...] this approach does not have an exact representation of zero, which is an important property to quantize padding and other zero-valued elements with no error." Instead, they compute the quantiles and normalize them. The infinite problem of $Q_x(0)$ is solved by evaluating the model with a very small number instead of 0. You can find the code related to this approach [here](https://github.com/TimDettmers/bitsandbytes/blob/0f40fa3f0a198802056e29ba183eaabc6751d565/bitsandbytes/functional.py#LL236C5-L236C22).
I hope it helps!

**Comment by Sapium59** [comment]
> I ran into the same doubt, and I found the implementation better explained in the paper "[NF4 Isn’t Information Theoretically Optimal](https://arxiv.org/pdf/2306.06965.pdf)." To explain it quickly, equation (4) is used for quantile quantization, but not for NormalFloat quantization because "[...] this approach does not have an exact representation of zero, which is an important property to quantize padding and other zero-valued elements with no error." Instead, they compute the quantiles and normalize them. The infinite problem of $Q_x(0)$ is solved by evaluating the model with a very small number instead of 0. You can find the code related to this approach [here](https://github.com/TimDettmers/bitsandbytes/blob/0f40fa3f0a198802056e29ba183eaabc6751d565/bitsandbytes/functional.py#LL236C5-L236C22).
> 
> This implementation should give you their results:
> 
> ```
> from scipy.stats import norm
> from scipy.interpolate import interp1d
> import numpy as np
> 
> n = 1000
> x = np.linspace(-4, 4, n)
> 
> cdf_values = norm.cdf(x, loc=0, scale=1)
> inverse_phi = interp1d(cdf_values, x, kind='linear')
> 
> delta = 1-0.9677083
> 
> # We compute the quantiles
> quantiles_negVal = [inverse_phi(negVal) for negVal in np.linspace(delta,0.5,8)] 
> quantiles_posVal = [inverse_phi(posVal) for posVal in np.linspace(0.5,1-delta,9)]
> 
> # We remove the 0 from the first quantiles
> quantiles = np.concatenate([quantiles_negVal[:-1],quantiles_posVal]) 
> quantiles_norm = quantiles/np.max(np.abs(quantiles))
> print(*map("{:.8f}".format, quantiles_norm), sep=" ")
> ```
That's it! Now the mechanism is quite clear. Thank you!

**Comment by vinodhchincholi** [comment]
Any particular reason the offset is ```delta = 1-0.9677083```? Alternatively delta equals (1/32 + 1/30) * 0.5.

**Comment by ziliwang** [comment]
As mentioned in the paper
> To ensure a discrete zeropoint of 0 and to use all $2^k$ bits for a k-bit datatype, we create an asymmetric
data type by estimating the quantiles qi of two ranges $q_{i}$: $2^{k}−1$ for the negative part and $2^{k}−1 + 1$ for
the positive part and then we unify these sets of $q_i$ and remove one of the two zeros that occurs in both
sets. 

and the author explain as

> - We want to find the quantiles which have equal area to the left and the right side of the quantile. This means, we do not start with the 0 or 1 quantile for the normal distribution, but with an offset quantile. This start position is called offset in the code snipped and is 1-1/(2x15). If we have an asymmetric data type, we have one side with spacing equivalent to 16 "halves" around each quantile and the other side with 15 halves. As such, the offset is on average (1-1/(2x15)+1-1/(2x16))/2 = 0.9677083.

**Comment by vinodhchincholi** [comment]
Thank you for taking the time to reply. It is still not clear to me, however. I see there's one quantile at 0. There are 7 quantiles to the left and 8 to the right of 0. Can you be a little more specific on how there's 15 halves on one side and 16 on the other? Which quantiles are we counting for?

**Comment by vinodhchincholi** [comment]
A quick calculation shows for ```k=4``` and ```i=8```, equation 4 evaluates to,
$q_8 = \frac{1}{2} \left( Q_X\left( \frac{8}{17} \right) + Q_X\left( \frac{9}{17} \right) \right) = \frac{1}{2}(-0.07379127 + 07379127) = 0$
Isn't this an exact representation of zero?

**Comment by sterngerlach** [comment]
> Isn't this an exact representation of zero?

I really think so!

In the current implementation (dQuantizeNF4() in bitsandbytes library), the value will be quantized to zero if it falls within a range of [-0.045525018125772476, 0.03979014977812767], which seems unintuitive to me because the range is asymmetric.
